name: Pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Build:
    name: Build Documentation and Deploy
    runs-on: ubuntu-latest
    environment:
      name: unturned.guide
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go (Most Recent @v4 Version)
        uses: actions/setup-go@v4

      - name: Install
        run: go install github.com/paganotoni/doco/cmd/doco@latest

      - name: Build
        run: doco build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public"
        
      - name: Deploy to unturned.guide
        id: deployment
        uses: actions/deploy-pages@v4
